### PR TITLE
moving team page information to prismic

### PR DESCRIPTION
**Pull request by Chris33871**
### Draft request to move the hardcoded team members' information from Vue to Prismic.

Way to test:
- Clone repo -> switch to branch -> npm run dev -> go to Prismic -> documents -> team -> eye icon -> view in localhost

**Do not publish the Prismic page as this will affect the live website.**

This pull request could be merged and the Prismic document published at the same time but there most likely is a better way of structuring the Prismic document and the code, hence the draft. 
Each team member has an associated link, those who did not have a link previously now have a link to the main bank.green, those who did have a link still have the same link (applies to Ilias and myself).

https://github.com/bank-green/nuxt-bank-green/assets/68507104/beb47e0c-267f-4f1a-b516-f47508787936

### CODE REVIEW

**Review by PooriaT — COMMENTED** [review]
It may need to add TeamMember.vue to solve the issue you've already mentioned.  "Could not find a component  for Slice type "teammember"

Just, try to add something like the below code and check whether the issue is solved. 

<template>
  <div class="teammember">
    
  </div>
</template>

<script>
export default {
  props: {
    // Define props here that match the fields in your slice
    name: String,
    href: String,
    description: String,
    img: String,
  },
};
</script>

**Comment by Chris33871** [comment]
Yes, that's what I think too. In the Slack comment, I mentioned that the TeamMember.vue slice needs to be created for the message to go away. 
Publishing the Prismic page doesn't automatically create that slice, unfortunately. The slice needs to be created manually. 

To make the warning message disappear in this push I used already-created slices. 

I'll try again using your suggested method as it would make Prismic less cluttered

**Comment by shuesken** [comment]
Hey @Chris33871 sorry for not commenting on this earlier. This clearly works but is also quite unelegant as you pointed out. The more native Prismic way of doing this would be to run the slicemachine with `npm run slicemachine`, create a `TeamMemberSlice` (probably with an Image Field and a Rich Text Field), set the "Slice Zone" in the `TeamPage` custom type to allow for `TeamMemberSlice`, save everything and sync the changes to Prismic. Then design the automatically created `TeamMemberSlice` component in `slices/TeamMemberSlice/index.vue`. You can have a look at how it's done with `SharePicGallerySlice`, which is also a single-purpose slice.

Also fyi you can generate shareable links for previews to save yourself having to click through Prismic for the preview. Here's one for previewing the team page on `localhost:3000`: https://prismic.link/470Cnxs

**Comment by Chris33871** [comment]
> Hey @Chris33871 sorry for not commenting on this earlier. This clearly works but is also quite unelegant as you pointed out. The more native Prismic way of doing this would be to run the slicemachine with `npm run slicemachine`, create a `TeamMemberSlice` (probably with an Image Field and a Rich Text Field), set the "Slice Zone" in the `TeamPage` custom type to allow for `TeamMemberSlice`, save everything and sync the changes to Prismic. Then design the automatically created `TeamMemberSlice` component in `slices/TeamMemberSlice/index.vue`. You can have a look at how it's done with `SharePicGallerySlice`, which is also a single-purpose slice.
> 
> Also fyi you can generate shareable links for previews to save yourself having to click through Prismic for the preview. Here's one for previewing the team page on `localhost:3000`: https://prismic.link/470Cnxs


Thank you for the feedback. 
Couple of things:
- I changed the code to make it look cleaner. Now I get the same warning I used to get saying that the component teammemberslice can't be found. I am guessing that I have to push the changes I made in the slicemachine for those changes to be resolved? (it would add the changes to the index.js file ?) 

- After adding the slice using the slicemachine, it created an index.ts file that if left alone creates errors in other parts of the code ([slug].vue page) so I deleted everything in the file. It is safe to completely delete that file correct?
The index.ts file seems to be a duplicate of the index.js file but in TypeScript.

**Comment by Chris33871** [comment]
@shuesken ,
Thank you very much, the embrace page is now properly synched 👍 
Working on the team page now

**Comment by ahmedlamidi** [comment]
I also found that to solve the not found problem you can manually add your slice in the index.js. I just copied the import scheme and it works.

**Pull request closed without merging**
