### PR TITLE
Optimize font size

### PR DESCRIPTION
**Pull request by vuphuctho**
Following this comment https://github.com/rsms/inter/issues/448 to exclude all characters/icons but Latin from the original font file `Inter-roman.var.woff`. New font file size is now 49kB.

To do:

- [x] check all pages to ensure new font file do not break anything.
- [x] the rest of the font files can also be optimized in the same way, too. Do let me know if we want to work on them.

### CODE REVIEW

**Comment by shuesken** [comment]
@vuphuctho  This is great! I don't think we use non-Latin characters and I couldn't find any in the blog posts. In an ideal world, we'd ship the full character set for fallback downloading if a character is encountered that isn't included, but I don't know how feasible that is. If it's something we can do with a CSS setting or something like that, it'd be great, otherwise this works for me.

And yes, I think we should optimize the other font as well.

**Review by shuesken — APPROVED** [review]

**Comment by vuphuctho** [comment]
@shuesken Based on the breakdown of language-supported in font file, there are a few levels:
- English/Minimal English: one of the base subsets, which only includes characters in English language.
- Latin: includes all characters frequently used in European languages
- Extended Latin: includes characters used in languages outside of European.

The Latin subset is actually good enough to cover most of our cases. If we need to support other non-Latin languages, i.e. Indian/Madarin/Japanese then we can add them in later. And I don't think there is a way to include fallback font files without downloading them.

References:
https://markoskon.com/creating-font-subsets
https://stackoverflow.com/a/14897846/2404452

**Comment by vuphuctho** [comment]
@shuesken Subsets for all font files have been added under postfix "Latin", and font.css now uses these new files instead of original.

Overall, the total font file size is cut down to 30% of original files.

I have quick check some pages: there is no issue so far. Please check if I missed anything.

**Comment by shuesken** [comment]
Looks good to me! If we do mis-display a character somewhere, we'll learn about it (and I'd consider that an acceptable risk).

**Pull request merged**
