### PR TITLE
chore: introduce linting recommended by nuxt

### PR DESCRIPTION
**Pull request by claudiabdm**
This is the linter configuration recommended by Nuxt in the [docs](https://nuxt.com/docs/guide/concepts/code-style#eslint):
- Add [@nuxt/eslint](https://eslint.nuxt.com/packages/module)
- Migrate old rules to [ eslint.config.mjs](https://github.com/bank-green/nuxt-bank-green/blob/fcdbf2d853b6e6a138462ff80bcb8dccfe2acf0d/eslint.config.mjs)
- Enable formatting with [ESLint Stylistic](https://eslint.nuxt.com/packages/module#eslint-stylistic)
- Enable checker in [dev server](https://eslint.nuxt.com/packages/module#dev-server-checker)

In addition, I added some new rules that were displaying an error after running the lint. We could agree what we do with those, like setting the message or disabling but these rules are recommended by vue/nuxt so maybe it's best not to disable them. 

I also auto fix and manually fix the errors the linter found but I can revert those commits. 

Next steps we could do: 
- Set up a [pre-commit hook](https://github.com/lint-staged/lint-staged) to run the linter before committing
- Add GitHub action

Let me know what you think!

### CODE REVIEW

**Comment by AlBillington** [comment]
I think it makes sense to include all the lint fixes as well, but perhaps as a fast follow? As long as dev works I think this is fine to push.  I think you should disable the "any" type check as well since its not really worth fixing these a lot of the time.

**Review by AlBillington — APPROVED** [review]
I think it makes sense to include all the lint fixes as well, but perhaps as a fast follow? As long as dev works I think this is fine to push. I think you should disable the "any" type check as well since its not really worth fixing these a lot of the time.

I added a couple things from my PR including a readme update and a fixer for just modified files

**Comment by claudiabdm** [comment]
Thanks!

I talked with @soph about autofixing errors and we agreed on doing so in another PR as well.

I could disable the "any" rule before merging but I think we should avoid using it as much as possible as it's not type-safe. It's just an escape from the typing system that should be used as a last resort and that's why "unknown" exists.

**Comment by AlBillington** [comment]
> Thanks!
> 
> We could disable the "any" rule before merging but I think we should avoid using it as much as possible as it's not type-safe. It's just an escape from the typing system that should be used as a last resort and that's why "unknown" exists.

your call, I have just found it to cause more headaches than it is worth

**Pull request merged**
