### PR TITLE
pe 592 sfi page image sizing

### PR DESCRIPTION
**Pull request by vuphuctho**
- Fix image sizing and alignment in SFI page
- Wrap text around image as per Figma design
- Polish mobile display

### CODE REVIEW

**Comment by shuesken** [comment]
@vuphuctho Ah this one looks tricky. Image sizing is good, but the column-break thing I think might be a hassle:

This kind of thing is confusing to read. I'm not certain that wrapping works so well flow-wise if the image is aligned left, but we should try to only break between bullet points. I believe this is somewhat configurable using the `widows` and `orphans` property as well as the `break-inside` or `break-before`, but I've never used that CSS.
image

On some screen sizes, the content now overflows:
image


I do think this might be tricky (and I see you had to dig into the prismic internals to make this work). If you feel the wrapping becoming too much of a headache, I'd be happy to drop it and just keep the proper image sizing.

**Comment by vuphuctho** [comment]
@shuesken Thanks for the suggestion. I think `break-inside` works in our case, though the alignment of two columns is hard to adjust. If it's still not good enough, I can revert back to commit [7294c30edda0cad070687df1b5c7706bb7e97b44](https://github.com/bank-green/nuxt-bank-green/tree/7294c30edda0cad070687df1b5c7706bb7e97b44) which has fix for the image size only and not the column CSS part.

**Comment by shuesken** [comment]
@vuphuctho This works great, but I'm not sure it always yields good-looking results either (see my screenshots in the ticket: https://linear.app/bankgreen/issue/PE-546/sfi-page-redesign#comment-41925e76 )
I'm out of my depth here design-wise though, so just asked Zak there for input.

**Comment by vuphuctho** [comment]
Reverted backs to grid instead of columns. Text content no longer spreads to second column. Images are resized to fit the tab content. @shuesken

**Review by shuesken — APPROVED** [review]

**Pull request merged**
