### PR TITLE
bank/[natwest] url case insensitivity implemented

### PR DESCRIPTION
**Pull request by Alexander-Sibhatu**
I had to sync the fork and fetch. That cleared out the PR (216), hence this PR is created.

### CODE REVIEW

**Review by RogerTangos — CHANGES_REQUESTED** [review]
Hey @Alexander-Sibhatu - this still needs work. While the tag.lowercase() is guaranteed to be unique, some brands do have tags with upper case letters. For example, `american_eagle_FCU`.

https://localhost:3000/banks/american_eagle_FCU is now broken.

All of these shoudl still work:

https://localhost:3000/banks/american_eagle_fcu
https://localhost:3000/banks/american_eagle_FCU 
https://localhost:3000/banks/natwest
https://localhost:3000/banks/Natwest

**Comment by RogerTangos** [comment]
sorry this wasn't an edge case I'd considered initially when we were grooming the tickets

**Comment by RogerTangos** [comment]
If this is complicated to impelment on FE, I could go through the database and cast everything to lowercase. I'd need to open a new BE ticket to sure the constraint is enforced though

**Comment by Alexander-Sibhatu** [comment]
Thanks. Let me see if I can fix this with the other urls. I will let you know shortly

**Comment by Alexander-Sibhatu** [comment]
Hi Albert, I don't see how this could be done. It would be much easier to handle it at the BE.

**Comment by RogerTangos** [comment]
Fixed in the BE. all BE tags are now lowercase

**Review by RogerTangos — APPROVED** [review]

**Pull request merged**
